Optimize Y Axis min value
Taewan-P/material-android-chart pull request #29
Opened 2024-05-05 17:57 UTC by Taewan-P

Previously, we optimize the y axis min value by setting the min axis value to the source data min value. Not just normalizing the tick value, we rounded the tick value to improve user experience because sometimes it can be hard to read the difference between each tick. However, this method still had a flaw. When the min value's last digits of the source data is not clean, the rounded tick can be still uncomfortable to read. To improve this, the min value of the axis is rounded down, and the rest of the logic that draws the gradation and graph lines are calculated based on the change min-max value.

**Before (Tick optimization before, after)**
<img width="300" alt="image" src="https://github.com/Taewan-P/material-android-chart/assets/27392567/428d3b40-0efb-4e14-b9e1-962fb0686903">

**After (Y axis min value optimization)**
<img width="300" alt="image" src="https://github.com/Taewan-P/material-android-chart/assets/27392567/7ddbcff2-5bfe-4a5f-b708-2f69483c2c00">

2024-05-08 09:08 UTC, ootr47 requested changes

2024-05-08 09:08 UTC, ootr47 commented on materialchart/src/main/java/app/priceguard/materialchart/Chart.kt
> +    private fun roundUpToSecondSignificantDigit(number: Float): Float {
It looks like you need to handle negative values ​​like you did in the roundDownToSecondSignificantDigit() function.

If the number coming as an argument is a negative number, a NaN error occurs.

2024-05-08 09:08 UTC, ootr47 commented on materialchart/src/main/java/app/priceguard/materialchart/Chart.kt
> +        }
If there are two or more of data, 
`difference = maxValue - minValue`
Since maxValue is always larger than realMinValue, it does not seem to be included in the else statement.

It seems that the else condition only comes in when there is 1 data, that is, when `difference = maxValue`. 
In this case, it is entered without a conditional statement.

So, I think this code will work without conditionals
`val unit = roundUpToSecondSignificantDigit(difference..`

2024-05-08 12:08 UTC, Taewan-P commented on materialchart/src/main/java/app/priceguard/materialchart/Chart.kt
> +        }
I was trying to find the edge cases on your statement, but couldn't find any. You're right! There is no need for this code.

While testing my sample edge cases, I found another bug related to rounding the significant digit. 
The bug occurs when the difference is small but the digits are large. The graph will have a huge body with small height changes on the top like the picture below. So I uploaded the fixed part as well with this part

<img width="382" alt="image" src="https://github.com/Taewan-P/material-android-chart/assets/27392567/1aa5fd80-6eda-4923-b1e8-6c97f940499d">

2024-05-08 12:16 UTC, Taewan-P commented on materialchart/src/main/java/app/priceguard/materialchart/Chart.kt
> +    private fun roundUpToSecondSignificantDigit(number: Float): Float {
Done! But I am not sure if rounding up & down is the same in negative numbers.
ex) -17321 -> -17300  In this case the rounds down but the actual value has increased. Shouldn't it be -17400?

2024-05-09 08:05 UTC, ootr47 commented on materialchart/src/main/java/app/priceguard/materialchart/Chart.kt
> +    private fun roundUpToSecondSignificantDigit(number: Float): Float {
How about rounding up if num is negative and rounding down otherwise?

`val roundedNumber = floor(absNumber / power) * power`
->
`val roundedNumber = if(num < 0) ceil(absNumber / power)*power else floor(absNumber / power) * power`

2024-05-09 16:25 UTC, Taewan-P commented on materialchart/src/main/java/app/priceguard/materialchart/Chart.kt
> +    private fun roundUpToSecondSignificantDigit(number: Float): Float {
Sounds like a good idea.

2024-05-10 08:37 UTC, ootr47 approved these changes
LGTM! 👍

2024-05-13 13:25 UTC, EunhoKang approved these changes
LGTM!

2024-05-13 13:25 UTC, merged